version: "2"
services:
  app_v11.0:
    image: app_v11.0
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
    networks:
      spnet:

